// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package postgres

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostgresServiceClient is the client API for PostgresService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostgresServiceClient interface {
	GetDatums(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDatumsResponse, error)
}

type postgresServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostgresServiceClient(cc grpc.ClientConnInterface) PostgresServiceClient {
	return &postgresServiceClient{cc}
}

func (c *postgresServiceClient) GetDatums(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDatumsResponse, error) {
	out := new(GetDatumsResponse)
	err := c.cc.Invoke(ctx, "/postgres.PostgresService/GetDatums", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostgresServiceServer is the server API for PostgresService service.
// All implementations must embed UnimplementedPostgresServiceServer
// for forward compatibility
type PostgresServiceServer interface {
	GetDatums(context.Context, *emptypb.Empty) (*GetDatumsResponse, error)
	mustEmbedUnimplementedPostgresServiceServer()
}

// UnimplementedPostgresServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPostgresServiceServer struct {
}

func (UnimplementedPostgresServiceServer) GetDatums(context.Context, *emptypb.Empty) (*GetDatumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatums not implemented")
}
func (UnimplementedPostgresServiceServer) mustEmbedUnimplementedPostgresServiceServer() {}

// UnsafePostgresServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostgresServiceServer will
// result in compilation errors.
type UnsafePostgresServiceServer interface {
	mustEmbedUnimplementedPostgresServiceServer()
}

func RegisterPostgresServiceServer(s grpc.ServiceRegistrar, srv PostgresServiceServer) {
	s.RegisterService(&PostgresService_ServiceDesc, srv)
}

func _PostgresService_GetDatums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgresServiceServer).GetDatums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postgres.PostgresService/GetDatums",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgresServiceServer).GetDatums(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PostgresService_ServiceDesc is the grpc.ServiceDesc for PostgresService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostgresService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "postgres.PostgresService",
	HandlerType: (*PostgresServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDatums",
			Handler:    _PostgresService_GetDatums_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "postgres.proto",
}
