// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc).

package postgres

import (
	"go.uber.org/zap"

	pb "immut-apt/api/postgres/v1"
)

// NewService is a constructor of a pb.PostgresServiceServer implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(logger *zap.Logger, querier *Queries) pb.PostgresServiceServer {
	return &Service{logger: logger, querier: querier}
}
